services:
  gym:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    tty: true
    container_name: gym_torch
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
      - $HOME/.aws:/root/.aws:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]