stages:
  train:
    cmd:
      python main.py ${train.Z} ${train.batch_size} ${train.num_epochs} data/${train.benign}
      data/${train.malware}
    deps:
      - data/${train.benign}
      - data/${train.malware}
    params:
      - train.Z
      - train.batch_size
      - train.num_epochs
      - train.benign
      - train.malware
    outs:
      - dynamic.yaml
  MCA:
    cmd: mca.py
    deps:
      - data/${train.benign}
      - data/${train.malware}
      - dynamic.yaml
    params:
      - dynamic.yaml:
          - malgan.id
      - train.mca
    outs:
      - data/${train.mca}
  testing:
    cmd: test
    params:
      - dynamic.yaml:
          - malgan.id
