stages:
  split:
    cmd: python scripts/split.py
    deps:
    - ${split.benign_dir}
    - ${split.malware_dir}
    outs:
    - ${train.benign}
    - ${train.malware}
    - ${valid.benign}
    - ${valid.malware}
    params:
    - split.test_size
    - split.random_state
    - split.benign_dir
    - split.malware_dir
  train_malgan:
    cmd: python main.py ${train.Z} ${train.batch_size} ${train.num_epochs} ${train.benign}
      ${train.malware}
    deps:
    - ${train.benign}
    - ${train.malware}
    params:
    - train.Z
    - train.batch_size
    - train.num_epochs
    - train.benign
    - train.malware
    - train.name
    outs:
    - dynamic.yaml:
        persist: true
  train_detector:
    cmd: python train_detector
    deps:
      - ${train.benign}
      - ${train.malware}
    params:
      - split.random_state
      - train.benign
      - train.malware
      - dynamic.yaml:
        - experiment.id
  train_mca:
    cmd: python mca.py
    deps:
    - ${train.benign}
    - ${train.malware}
    params:
    - dynamic.yaml:
      - experiment.id
    - train.mca
    - train.estimators
    - train.head
    outs:
    - ${train.mca}:
        persist: true
  graph_mca:
    cmd: python scripts/graph_mca.py
    deps:
      - ${train.mca}
    outs:
      - outs/mca_scatter.html
  train_mca_classifier:
    cmd: python mca_classifier.py
    deps:
    - ${train.mca}
    params:
    - train.mca
    - train.estimators
    - dynamic.yaml:
      - experiment.id
  extract_normal_features:
    cmd: python lime_normal.py
    deps:
    - ${train.benign}
    - ${train.mca}
    outs:
    - ${train.normal_features}:
        persist: true
    params:
    - train.benign
    - train.mca
    - train.normal_features
    - dynamic.yaml:
      - experiment.id
  experiment_base:
    cmd: PYTHONHASHSEED=0 python experiment.py normal
    deps:
      - ${valid.benign}
      - ${valid.malware}
    params:
      - valid.benign
      - valid.malware
      - metrics.normal
      - dynamic.yaml:
        - experiment.id
    metrics:
      - ${metrics.normal}
    outs:
      - ${metrics.normal_confusion}
  experiment_lime:
    cmd: PYTHONHASHSEED=0 python experiment.py lime
    deps:
      - ${valid.benign}
      - ${valid.malware}
      - ${train.mca}
    params:
      - valid.benign
      - valid.malware
      - train.mca
      - train.normal_features
      - dynamic.yaml:
        - experiment.id
    metrics:
      - ${metrics.lime}
      - ${metrics.lime_obf}
    outs:
      - ${metrics.lime_confusion}
      - ${metrics.lime_confusion_obf}
