stages:
  split:
    cmd: python scripts/split.py
    deps:
      - ${split.benign_dir}
      - ${split.malware_dir}
    outs:
      - ${train.benign}
      - ${train.malware}
      - ${valid.benign}
      - ${valid.malware}
    params:
      - split.test_size
      - split.random_state
      - split.benign_dir
      - split.malware_dir
  train_malgan:
    cmd: python main.py ${train.Z} ${train.batch_size} ${train.num_epochs} ${train.benign} ${train.malware}
    deps:
      - ${train.benign}
      - ${train.malware}
    params:
      - train.Z
      - train.batch_size
      - train.num_epochs
      - train.benign
      - train.malware
    outs:
      - dynamic.yaml
  train_mca:
    cmd: python mca.py
    deps:
      - ${train.benign}
      - ${train.malware}
      - dynamic.yaml
    params:
      - dynamic.yaml:
          - experiment.id
      - train.mca
    outs:
      - ${train.mca}
  graph_mca:
    cmd: python scripts/graph_mca.py
    deps:
      - ${train.mca}
  train_mca_classifier:
    cmd: python mca_classifier.py
    deps:
      - dynamic.yaml
    params:
      - train.mca
      - train.estimators
      - dynamic.yaml:
          - experiment.id
