split:
  test_size: 0.2
  random_state: 42
  benign_dir: data/raw/sleipnir/benign
  malware_dir: data/raw/sleipnir/malicious
train:
  Z: 100
  batch_size: 32
  num_epochs: 32
  activation: tanh
  benign: data/train/ben.npy
  malware: data/train/mal.npy
  mca: data/MCA.csv
  normal_features: data/normal_features.txt
  name: Bachelor_2000
  estimators: 200
  head: 1000
valid:
  benign: data/valid/ben.npy
  malware: data/valid/mal.npy
metrics:
  normal: metrics/normal.json
  lime: metrics/lime.json
  lime_obf: metrics/lime_obf.json
  normal_confusion: metrics/normal.png
  lime_confusion: metrics/lime.png
  lime_confusion_obf: metrics/lime_obf.png
