split:
  test_size: 0.2
  random_state: 42
  benign_dir: data/raw/sleipnir/benign
  malware_dir: data/raw/sleipnir/malicious
train:
  Z: 10
  batch_size: 32
  num_epochs: 1
  benign: data/train/ben.npy
  malware: data/train/mal.npy
  mca: data/MCA.csv
  normal_features: data/normal_features.txt
  name: Bachelor_2000
  estimators: 100
  head: 1000
valid:
  benign: data/valid/ben.npy
  malware: data/valid/mal.npy
