split:
  test_size: 0.2
  random_state: 42
  unique_ratio: 0.7
  benign_dir: data/raw/sleipnir/benign
  malware_dir: data/raw/sleipnir/malicious
train:
  Z: 100
  gen_hidden: 256 512 512 256
  batch_size: 32
  num_epochs: 500
  activation: leakyrelu
  benign: data/train/ben.npy
  malware: data/train/mal.npy
  mca: data/MCA.csv
  normal_features: data/normal_features.txt
  normal_categorical_features: data/normal_categorical_features.txt
  name: Layer_increase_higher_LR
  estimators: 10
  head: 1500
  num_features: 200
  mca_components: 50
valid:
  benign: data/valid/ben.npy
  malware: data/valid/mal.npy
  lime_scale: 100000
metrics:
  normal: metrics/normal.json
  lime: metrics/lime.json
  lime_obf: metrics/lime_obf.json
  lime_cat: metrics/lime_cat.json
  lime_cat_obf: metrics/lime_cat_obf.json
  normal_confusion: metrics/normal.png
  lime_confusion: metrics/lime.png
  lime_confusion_obf: metrics/lime_obf.png
  lime_cat_confusion: metrics/lime_cat.png
  lime_cat_confusion_obf: metrics/lime_cat_obf.png
